data_full <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?")
data1 <- subset(data_full, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")

datetime<-paste(data1$Date,data1$Time)
data1$datetime<-as.POSIXct(datetime)
with(data1,plot(Sub_metering_1~datetime,type="l",xlab="",ylab="Energy Sub metering"))
with(data1,lines(Sub_metering_2~datetime,type="l",col="red"))
with(data1,lines(Sub_metering_3~datetime,type="l",col="blue"))
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=2,lty=1)
dev.copy(png,"plot3.png",height=480,width=480)
dev.off()
